M48
; DRILL file {KiCad 8.0.6} date 2024-11-24T18:57:19+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-24T18:57:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X7.3823Y-3.4213
X7.6098Y-3.4213
T2
X7.3567Y-3.0157
M30
