// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
void ui_event_InitScreen(lv_event_t *e);
lv_obj_t *ui_InitScreen;
lv_obj_t *ui_InitScreen_Image2;
lv_obj_t *ui_InitScreen_mainLabel;
// CUSTOM VARIABLES

// SCREEN: ui_ProfileScreen
void ui_ProfileScreen_screen_init(void);
void ui_event_ProfileScreen(lv_event_t *e);
lv_obj_t *ui_ProfileScreen;
lv_obj_t *ui_ProfileScreen_tempTarget;
lv_obj_t *ui_ProfileScreen_tempGauge;
lv_obj_t *ui_ProfileScreen_ImgButton1;
lv_obj_t *ui_ProfileScreen_contentPanel;
lv_obj_t *ui_ProfileScreen_mainLabel;
void ui_event_ProfileScreen_profileChoices(lv_event_t *e);
lv_obj_t *ui_ProfileScreen_profileChoices;
lv_obj_t *ui_ProfileScreen_tempText;
// CUSTOM VARIABLES

// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
lv_obj_t *ui_MenuScreen;
lv_obj_t *ui_MenuScreen_tempTarget;
lv_obj_t *ui_MenuScreen_tempGauge;
lv_obj_t *ui_MenuScreen_pressureTarget;
lv_obj_t *ui_MenuScreen_pressureGauge;
void ui_event_MenuScreen_standbyButton(lv_event_t *e);
lv_obj_t *ui_MenuScreen_standbyButton;
lv_obj_t *ui_MenuScreen_contentPanel1;
void ui_event_MenuScreen_btnBrew(lv_event_t *e);
lv_obj_t *ui_MenuScreen_btnBrew;
void ui_event_MenuScreen_btnSteam(lv_event_t *e);
lv_obj_t *ui_MenuScreen_btnSteam;
void ui_event_MenuScreen_waterBtn(lv_event_t *e);
lv_obj_t *ui_MenuScreen_waterBtn;
void ui_event_MenuScreen_grindBtn(lv_event_t *e);
lv_obj_t *ui_MenuScreen_grindBtn;
lv_obj_t *ui_MenuScreen_pressureText;
lv_obj_t *ui_MenuScreen_tempText;
// CUSTOM VARIABLES

// SCREEN: ui_BrewScreen
void ui_BrewScreen_screen_init(void);
void ui_event_BrewScreen(lv_event_t *e);
lv_obj_t *ui_BrewScreen;
lv_obj_t *ui_BrewScreen_tempTarget;
lv_obj_t *ui_BrewScreen_tempGauge;
lv_obj_t *ui_BrewScreen_ImgButton5;
lv_obj_t *ui_BrewScreen_contentPanel4;
lv_obj_t *ui_BrewScreen_mainLabel3;
void ui_event_BrewScreen_startButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_startButton;
lv_obj_t *ui_BrewScreen_tempText;
lv_obj_t *ui_BrewScreen_controlContainer;
lv_obj_t *ui_BrewScreen_modeSwitch;
void ui_event_BrewScreen_timedButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_timedButton;
void ui_event_BrewScreen_volumetricButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_volumetricButton;
lv_obj_t *ui_BrewScreen_tempContainer;
lv_obj_t *ui_BrewScreen_targetTemp;
void ui_event_BrewScreen_downTempButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_downTempButton;
void ui_event_BrewScreen_upTempButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_upTempButton;
lv_obj_t *ui_BrewScreen_Image5;
lv_obj_t *ui_BrewScreen_targetContainer;
lv_obj_t *ui_BrewScreen_targetDuration;
void ui_event_BrewScreen_upDurationButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_upDurationButton;
void ui_event_BrewScreen_downDurationButton(lv_event_t *e);
lv_obj_t *ui_BrewScreen_downDurationButton;
lv_obj_t *ui_BrewScreen_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_SteamScreen
void ui_SteamScreen_screen_init(void);
void ui_event_SteamScreen(lv_event_t *e);
lv_obj_t *ui_SteamScreen;
lv_obj_t *ui_SteamScreen_tempTarget;
lv_obj_t *ui_SteamScreen_tempGauge;
lv_obj_t *ui_SteamScreen_ImgButton6;
lv_obj_t *ui_SteamScreen_contentPanel5;
lv_obj_t *ui_SteamScreen_mainLabel5;
void ui_event_SteamScreen_goButton(lv_event_t *e);
lv_obj_t *ui_SteamScreen_goButton;
void ui_event_SteamScreen_downTempButton(lv_event_t *e);
lv_obj_t *ui_SteamScreen_downTempButton;
void ui_event_SteamScreen_upTempButton(lv_event_t *e);
lv_obj_t *ui_SteamScreen_upTempButton;
lv_obj_t *ui_SteamScreen_targetTemp;
lv_obj_t *ui_SteamScreen_Image9;
lv_obj_t *ui_SteamScreen_tempText;
// CUSTOM VARIABLES

// SCREEN: ui_WaterScreen
void ui_WaterScreen_screen_init(void);
void ui_event_WaterScreen(lv_event_t *e);
lv_obj_t *ui_WaterScreen;
lv_obj_t *ui_WaterScreen_tempTarget;
lv_obj_t *ui_WaterScreen_tempGauge;
lv_obj_t *ui_WaterScreen_ImgButton7;
lv_obj_t *ui_WaterScreen_contentPanel6;
lv_obj_t *ui_WaterScreen_mainLabel6;
void ui_event_WaterScreen_goButton(lv_event_t *e);
lv_obj_t *ui_WaterScreen_goButton;
void ui_event_WaterScreen_downTempButton(lv_event_t *e);
lv_obj_t *ui_WaterScreen_downTempButton;
void ui_event_WaterScreen_upTempButton(lv_event_t *e);
lv_obj_t *ui_WaterScreen_upTempButton;
lv_obj_t *ui_WaterScreen_targetTemp;
lv_obj_t *ui_WaterScreen_Image10;
lv_obj_t *ui_WaterScreen_tempText;
// CUSTOM VARIABLES

// SCREEN: ui_StandbyScreen
void ui_StandbyScreen_screen_init(void);
void ui_event_StandbyScreen(lv_event_t *e);
lv_obj_t *ui_StandbyScreen;
lv_obj_t *ui_StandbyScreen_Image1;
lv_obj_t *ui_StandbyScreen_time;
lv_obj_t *ui_StandbyScreen_Container1;
lv_obj_t *ui_StandbyScreen_wifiIcon;
lv_obj_t *ui_StandbyScreen_bluetoothIcon;
lv_obj_t *ui_StandbyScreen_updateIcon;
lv_obj_t *ui_StandbyScreen_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_StatusScreen
void ui_StatusScreen_screen_init(void);
void ui_event_StatusScreen(lv_event_t *e);
lv_obj_t *ui_StatusScreen;
lv_obj_t *ui_StatusScreen_tempTarget;
lv_obj_t *ui_StatusScreen_tempGauge;
lv_obj_t *ui_StatusScreen_ImgButton3;
lv_obj_t *ui_StatusScreen_contentPanel2;
lv_obj_t *ui_StatusScreen_targetDuration;
lv_obj_t *ui_StatusScreen_targetTemp;
void ui_event_StatusScreen_pauseButton(lv_event_t *e);
lv_obj_t *ui_StatusScreen_pauseButton;
lv_obj_t *ui_StatusScreen_Image7;
lv_obj_t *ui_StatusScreen_Image8;
lv_obj_t *ui_StatusScreen_currentDuration;
lv_obj_t *ui_StatusScreen_stepLabel;
lv_obj_t *ui_StatusScreen_phaseLabel;
lv_obj_t *ui_StatusScreen_barContainer;
lv_obj_t *ui_StatusScreen_preinfusePumpBar;
lv_obj_t *ui_StatusScreen_preinfuseBloomBar;
lv_obj_t *ui_StatusScreen_brewPumpBar;
lv_obj_t *ui_StatusScreen_brewBar;
lv_obj_t *ui_StatusScreen_labelContainer;
lv_obj_t *ui_StatusScreen_preinfusePumpLabel;
lv_obj_t *ui_StatusScreen_preinfuseBloomLabel;
lv_obj_t *ui_StatusScreen_brewPumpLabel;
lv_obj_t *ui_StatusScreen_brewLabel;
lv_obj_t *ui_StatusScreen_tempText;
// CUSTOM VARIABLES

// SCREEN: ui_GrindScreen
void ui_GrindScreen_screen_init(void);
void ui_event_GrindScreen(lv_event_t *e);
lv_obj_t *ui_GrindScreen;
lv_obj_t *ui_GrindScreen_tempTarget;
lv_obj_t *ui_GrindScreen_tempGauge;
lv_obj_t *ui_GrindScreen_ImgButton2;
lv_obj_t *ui_GrindScreen_contentPanel7;
lv_obj_t *ui_GrindScreen_mainLabel7;
void ui_event_GrindScreen_startButton(lv_event_t *e);
lv_obj_t *ui_GrindScreen_startButton;
void ui_event_GrindScreen_downDurationButton(lv_event_t *e);
lv_obj_t *ui_GrindScreen_downDurationButton;
void ui_event_GrindScreen_upDurationButton(lv_event_t *e);
lv_obj_t *ui_GrindScreen_upDurationButton;
lv_obj_t *ui_GrindScreen_targetDuration;
lv_obj_t *ui_GrindScreen_Image11;
lv_obj_t *ui_GrindScreen_tempText;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_459451241[1] = {&ui_img_1829139226};
const lv_img_dsc_t *ui_imgset_434888472[1] = {&ui_img_295763949};
const lv_img_dsc_t *ui_imgset_1091184723[1] = {&ui_img_1091371356};
const lv_img_dsc_t *ui_imgset_960046369[1] = {&ui_img_631115820};
const lv_img_dsc_t *ui_imgset_1525119997[1] = {&ui_img_360122106};
const lv_img_dsc_t *ui_imgset_1812359778[1] = {&ui_img_363557387};
const lv_img_dsc_t *ui_imgset_359218129[1] = {&ui_img_1424216268};
const lv_img_dsc_t *ui_imgset_403384789[1] = {&ui_img_834125362};
const lv_img_dsc_t *ui_imgset_359534444[1] = {&ui_img_979979123};
const lv_img_dsc_t *ui_imgset_794559649[1] = {&ui_img_1456692430};
const lv_img_dsc_t *ui_imgset_1612577215[1] = {&ui_img_445946954};
const lv_img_dsc_t *ui_imgset_1166435085[1] = {&ui_img_390988422};
const lv_img_dsc_t *ui_imgset_1010926578[1] = {&ui_img_2044104741};
const lv_img_dsc_t *ui_imgset_1155213431[1] = {&ui_img_545340440};
const lv_img_dsc_t *ui_imgset_524469952[1] = {&ui_img_1765671371};
const lv_img_dsc_t *ui_imgset_690294202[1] = {&ui_img_1732953241};
const lv_img_dsc_t *ui_imgset_1252186405[1] = {&ui_img_1951499226};
const lv_img_dsc_t *ui_imgset_2074400918[1] = {&ui_img_364513079};
const lv_img_dsc_t *ui_imgset_506671969[1] = {&ui_img_783005998};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_InitScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOADED) {
        onLoadStarted(e);
    }
}

void ui_event_ProfileScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
}

void ui_event_ProfileScreen_profileChoices(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_StatusScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StatusScreen_screen_init);
    }
}

void ui_event_MenuScreen_standbyButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onStandby(e);
    }
}

void ui_event_MenuScreen_btnBrew(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewScreen(e);
    }
}

void ui_event_MenuScreen_btnSteam(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamScreen(e);
    }
}

void ui_event_MenuScreen_waterBtn(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onWaterScreen(e);
    }
}

void ui_event_MenuScreen_grindBtn(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onGrindScreen(e);
    }
}

void ui_event_BrewScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
}

void ui_event_BrewScreen_startButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewStart(e);
    }
}

void ui_event_BrewScreen_timedButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onTimedClick(e);
    }
}

void ui_event_BrewScreen_volumetricButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onVolumetricClick(e);
    }
}

void ui_event_BrewScreen_downTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTempLower(e);
    }
}

void ui_event_BrewScreen_upTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTempRaise(e);
    }
}

void ui_event_BrewScreen_upDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTimeRaise(e);
    }
}

void ui_event_BrewScreen_downDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTimeLower(e);
    }
}

void ui_event_SteamScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
}

void ui_event_SteamScreen_goButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamToggle(e);
    }
}

void ui_event_SteamScreen_downTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamTempLower(e);
    }
}

void ui_event_SteamScreen_upTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onSteamTempRaise(e);
    }
}

void ui_event_WaterScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MenuScreen_screen_init);
        onMenuClick(e);
    }
}

void ui_event_WaterScreen_goButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onWaterToggle(e);
    }
}

void ui_event_WaterScreen_downTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onWaterTempLower(e);
    }
}

void ui_event_WaterScreen_upTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onWaterTempRaise(e);
    }
}

void ui_event_StandbyScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED) {
        onWakeup(e);
    }
}

void ui_event_StatusScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
}

void ui_event_StatusScreen_pauseButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewCancel(e);
        (e);
        _ui_screen_change(&ui_BrewScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_BrewScreen_screen_init);
    }
}

void ui_event_GrindScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
}

void ui_event_GrindScreen_startButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onGrindToggle(e);
    }
}

void ui_event_GrindScreen_downDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onGrindTimeLower(e);
    }
}

void ui_event_GrindScreen_upDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onGrindTimeRaise(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme =
        lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_InitScreen_screen_init();
    ui_MenuScreen_screen_init();
    ui_BrewScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_InitScreen);
}
