// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _GAGGIMATE_UI_H
#define _GAGGIMATE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_helpers.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
void ui_event_InitScreen(lv_event_t *e);
extern lv_obj_t *ui_InitScreen;
extern lv_obj_t *ui_InitScreen_Image2;
extern lv_obj_t *ui_InitScreen_mainLabel;
// CUSTOM VARIABLES

// SCREEN: ui_ProfileScreen
void ui_ProfileScreen_screen_init(void);
void ui_event_ProfileScreen(lv_event_t *e);
extern lv_obj_t *ui_ProfileScreen;
extern lv_obj_t *ui_ProfileScreen_dials;
void ui_event_ProfileScreen_ImgButton1(lv_event_t *e);
extern lv_obj_t *ui_ProfileScreen_ImgButton1;
extern lv_obj_t *ui_ProfileScreen_contentPanel;
void ui_event_ProfileScreen_previousProfileBtn(lv_event_t *e);
extern lv_obj_t *ui_ProfileScreen_previousProfileBtn;
void ui_event_ProfileScreen_nextProfileBtn(lv_event_t *e);
extern lv_obj_t *ui_ProfileScreen_nextProfileBtn;
extern lv_obj_t *ui_ProfileScreen_loadingSpinner;
extern lv_obj_t *ui_ProfileScreen_profileDetails;
void ui_event_ProfileScreen_chooseButton(lv_event_t *e);
extern lv_obj_t *ui_ProfileScreen_chooseButton;
extern lv_obj_t *ui_ProfileScreen_simpleContent;
extern lv_obj_t *ui_ProfileScreen_phasesLabel;
extern lv_obj_t *ui_ProfileScreen_stepsLabel;
extern lv_obj_t *ui_ProfileScreen_extendedContent;
extern lv_obj_t *ui_ProfileScreen_Chart1;
extern lv_obj_t *ui_ProfileScreen_mainLabel;
extern lv_obj_t *ui_ProfileScreen_profileName;
extern lv_obj_t *ui_ProfileScreen_tempIcon;
extern lv_obj_t *ui_ProfileScreen_targetIcon;
extern lv_obj_t *ui_ProfileScreen_targetTemp2;
extern lv_obj_t *ui_ProfileScreen_targetDuration2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ProfileScreen_dials_tempGauge;
extern lv_obj_t *uic_ProfileScreen_dials_tempTarget;
extern lv_obj_t *uic_ProfileScreen_dials_pressureGauge;
extern lv_obj_t *uic_ProfileScreen_dials_pressureTarget;
extern lv_obj_t *uic_ProfileScreen_dials_pressureText;
extern lv_obj_t *uic_ProfileScreen_dials_tempText;

// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
void ui_event_MenuScreen(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen;
extern lv_obj_t *ui_MenuScreen_dials;
void ui_event_MenuScreen_standbyButton(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen_standbyButton;
extern lv_obj_t *ui_MenuScreen_contentPanel1;
void ui_event_MenuScreen_btnBrew(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen_btnBrew;
void ui_event_MenuScreen_btnSteam(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen_btnSteam;
void ui_event_MenuScreen_waterBtn(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen_waterBtn;
void ui_event_MenuScreen_grindBtn(lv_event_t *e);
extern lv_obj_t *ui_MenuScreen_grindBtn;
// CUSTOM VARIABLES
extern lv_obj_t *uic_MenuScreen_dials_tempGauge;
extern lv_obj_t *uic_MenuScreen_dials_tempTarget;
extern lv_obj_t *uic_MenuScreen_dials_pressureGauge;
extern lv_obj_t *uic_MenuScreen_dials_pressureTarget;
extern lv_obj_t *uic_MenuScreen_dials_pressureText;
extern lv_obj_t *uic_MenuScreen_dials_tempText;

// SCREEN: ui_BrewScreen
void ui_BrewScreen_screen_init(void);
void ui_event_BrewScreen(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen;
extern lv_obj_t *ui_BrewScreen_dials;
void ui_event_BrewScreen_ImgButton5(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_ImgButton5;
extern lv_obj_t *ui_BrewScreen_contentPanel4;
extern lv_obj_t *ui_BrewScreen_mainLabel3;
void ui_event_BrewScreen_startButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_startButton;
extern lv_obj_t *ui_BrewScreen_controlContainer;
extern lv_obj_t *ui_BrewScreen_modeSwitch;
void ui_event_BrewScreen_timedButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_timedButton;
void ui_event_BrewScreen_volumetricButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_volumetricButton;
extern lv_obj_t *ui_BrewScreen_profileInfo;
extern lv_obj_t *ui_BrewScreen_Label1;
extern lv_obj_t *ui_BrewScreen_Container3;
extern lv_obj_t *ui_BrewScreen_profileName;
void ui_event_BrewScreen_profileSelectBtn(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_profileSelectBtn;
extern lv_obj_t *ui_BrewScreen_adjustments;
extern lv_obj_t *ui_BrewScreen_tempContainer;
extern lv_obj_t *ui_BrewScreen_targetTemp;
void ui_event_BrewScreen_downTempButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_downTempButton;
void ui_event_BrewScreen_upTempButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_upTempButton;
extern lv_obj_t *ui_BrewScreen_Image5;
extern lv_obj_t *ui_BrewScreen_targetContainer;
extern lv_obj_t *ui_BrewScreen_targetDuration;
void ui_event_BrewScreen_upDurationButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_upDurationButton;
void ui_event_BrewScreen_downDurationButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_downDurationButton;
extern lv_obj_t *ui_BrewScreen_Image4;
// CUSTOM VARIABLES
extern lv_obj_t *uic_BrewScreen_dials_tempGauge;
extern lv_obj_t *uic_BrewScreen_dials_tempTarget;
extern lv_obj_t *uic_BrewScreen_dials_pressureGauge;
extern lv_obj_t *uic_BrewScreen_dials_pressureTarget;
extern lv_obj_t *uic_BrewScreen_dials_pressureText;
extern lv_obj_t *uic_BrewScreen_dials_tempText;

// SCREEN: ui_SimpleProcessScreen
void ui_SimpleProcessScreen_screen_init(void);
void ui_event_SimpleProcessScreen(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen;
extern lv_obj_t *ui_SimpleProcessScreen_dials;
void ui_event_SimpleProcessScreen_ImgButton6(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_ImgButton6;
extern lv_obj_t *ui_SimpleProcessScreen_contentPanel5;
extern lv_obj_t *ui_SimpleProcessScreen_mainLabel5;
void ui_event_SimpleProcessScreen_goButton(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_goButton;
void ui_event_SimpleProcessScreen_downTempButton(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_downTempButton;
void ui_event_SimpleProcessScreen_upTempButton(lv_event_t *e);
extern lv_obj_t *ui_SimpleProcessScreen_upTempButton;
extern lv_obj_t *ui_SimpleProcessScreen_targetTemp;
extern lv_obj_t *ui_SimpleProcessScreen_Image9;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempGauge;
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempTarget;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureGauge;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureTarget;
extern lv_obj_t *uic_SimpleProcessScreen_dials_pressureText;
extern lv_obj_t *uic_SimpleProcessScreen_dials_tempText;

// SCREEN: ui_StandbyScreen
void ui_StandbyScreen_screen_init(void);
void ui_event_StandbyScreen(lv_event_t *e);
extern lv_obj_t *ui_StandbyScreen;
extern lv_obj_t *ui_StandbyScreen_Image1;
extern lv_obj_t *ui_StandbyScreen_time;
extern lv_obj_t *ui_StandbyScreen_Container1;
extern lv_obj_t *ui_StandbyScreen_wifiIcon;
extern lv_obj_t *ui_StandbyScreen_bluetoothIcon;
extern lv_obj_t *ui_StandbyScreen_updateIcon;
extern lv_obj_t *ui_StandbyScreen_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_StatusScreen
void ui_StatusScreen_screen_init(void);
void ui_event_StatusScreen(lv_event_t *e);
extern lv_obj_t *ui_StatusScreen;
extern lv_obj_t *ui_StatusScreen_dials;
void ui_event_StatusScreen_ImgButton8(lv_event_t *e);
extern lv_obj_t *ui_StatusScreen_ImgButton8;
extern lv_obj_t *ui_StatusScreen_contentPanel2;
extern lv_obj_t *ui_StatusScreen_targetDuration;
extern lv_obj_t *ui_StatusScreen_targetTemp;
void ui_event_StatusScreen_pauseButton(lv_event_t *e);
extern lv_obj_t *ui_StatusScreen_pauseButton;
extern lv_obj_t *ui_StatusScreen_Image7;
extern lv_obj_t *ui_StatusScreen_Image8;
extern lv_obj_t *ui_StatusScreen_currentDuration;
extern lv_obj_t *ui_StatusScreen_stepLabel;
extern lv_obj_t *ui_StatusScreen_phaseLabel;
extern lv_obj_t *ui_StatusScreen_barContainer;
extern lv_obj_t *ui_StatusScreen_brewBar;
extern lv_obj_t *ui_StatusScreen_labelContainer;
extern lv_obj_t *ui_StatusScreen_brewLabel;
extern lv_obj_t *ui_StatusScreen_brewVolume;
// CUSTOM VARIABLES
extern lv_obj_t *uic_StatusScreen_dials_tempGauge;
extern lv_obj_t *uic_StatusScreen_dials_tempTarget;
extern lv_obj_t *uic_StatusScreen_dials_pressureGauge;
extern lv_obj_t *uic_StatusScreen_dials_pressureTarget;
extern lv_obj_t *uic_StatusScreen_dials_pressureText;
extern lv_obj_t *uic_StatusScreen_dials_tempText;

// SCREEN: ui_GrindScreen
void ui_GrindScreen_screen_init(void);
void ui_event_GrindScreen(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen;
extern lv_obj_t *ui_GrindScreen_dials;
void ui_event_GrindScreen_ImgButton2(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_ImgButton2;
extern lv_obj_t *ui_GrindScreen_contentPanel7;
extern lv_obj_t *ui_GrindScreen_mainLabel7;
void ui_event_GrindScreen_startButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_startButton;
extern lv_obj_t *ui_GrindScreen_targetContainer;
extern lv_obj_t *ui_GrindScreen_targetDuration;
void ui_event_GrindScreen_upDurationButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_upDurationButton;
void ui_event_GrindScreen_downDurationButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_downDurationButton;
extern lv_obj_t *ui_GrindScreen_targetSymbol;
extern lv_obj_t *ui_GrindScreen_modeSwitch;
void ui_event_GrindScreen_timedButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_timedButton;
void ui_event_GrindScreen_volumetricButton(lv_event_t *e);
extern lv_obj_t *ui_GrindScreen_volumetricButton;
// CUSTOM VARIABLES
extern lv_obj_t *uic_GrindScreen_dials_tempGauge;
extern lv_obj_t *uic_GrindScreen_dials_tempTarget;
extern lv_obj_t *uic_GrindScreen_dials_pressureGauge;
extern lv_obj_t *uic_GrindScreen_dials_pressureTarget;
extern lv_obj_t *uic_GrindScreen_dials_pressureText;
extern lv_obj_t *uic_GrindScreen_dials_tempText;

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);     // assets/logo.png
LV_IMG_DECLARE(ui_img_untitled_png); // assets/Untitled.png
LV_IMG_DECLARE(ui_img_489054950);    // assets/gauge-fill.png
LV_IMG_DECLARE(ui_img_340686386);    // assets/indicator-small.png
LV_IMG_DECLARE(ui_img_1455708189);   // assets/pressure-filled.png
LV_IMG_DECLARE(ui_img_1951499226);   // assets/thermometer-half-40x40.png
LV_IMG_DECLARE(ui_img_1220767159);   // assets/tachometer-fast-40x40.png
LV_IMG_DECLARE(ui_img_295763949);    // assets/angle-up-40x40.png
LV_IMG_DECLARE(ui_img_98036921);     // assets/angle-left-40x40.png
LV_IMG_DECLARE(ui_img_944513416);    // assets/angle-right-40x40.png
LV_IMG_DECLARE(ui_img_631115820);    // assets/check-40x40.png
LV_IMG_DECLARE(ui_img_360122106);    // assets/clock-40x40.png
LV_IMG_DECLARE(ui_img_2044104741);   // assets/power-40x40.png
LV_IMG_DECLARE(ui_img_979979123);    // assets/mug-hot-alt-80x80.png
LV_IMG_DECLARE(ui_img_783005998);    // assets/wind-80x80.png
LV_IMG_DECLARE(ui_img_545340440);    // assets/raindrops-80x80.png
LV_IMG_DECLARE(ui_img_363557387);    // assets/coffee-bean-80x80.png
LV_IMG_DECLARE(ui_img_445946954);    // assets/play-40x40.png
LV_IMG_DECLARE(ui_img_1424216268);   // assets/equality-40x40.png
LV_IMG_DECLARE(ui_img_332059803);    // assets/dropdown-bar-40x40.png
LV_IMG_DECLARE(ui_img_834125362);    // assets/minus-small-40x40.png
LV_IMG_DECLARE(ui_img_390988422);    // assets/plus-small-40x40.png
LV_IMG_DECLARE(ui_img_364513079);    // assets/wifi-20x20.png
LV_IMG_DECLARE(ui_img_1091371356);   // assets/bluetooth-alt-20x20.png
LV_IMG_DECLARE(ui_img_1765671371);   // assets/refresh-20x20.png
LV_IMG_DECLARE(ui_img_1732953241);   // assets/tap-60x60.png
LV_IMG_DECLARE(ui_img_1456692430);   // assets/pause-40x40.png
LV_IMG_DECLARE(ui_img_1829139226);   // assets/angle-down-40x40.png
LV_IMG_DECLARE(ui_img_340148213);    // assets/settings-40x40.png
LV_IMG_DECLARE(ui_img_691326438);    // assets/wind-40x40.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
