// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

void ui_GrindScreen_screen_init(void)
{
    ui_GrindScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GrindScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_GrindScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_GrindScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    ui_GrindScreen_tempTarget = lv_img_create(ui_GrindScreen);
    lv_img_set_src(ui_GrindScreen_tempTarget, &ui_img_indicator_png);
    lv_obj_set_width(ui_GrindScreen_tempTarget, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GrindScreen_tempTarget, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GrindScreen_tempTarget, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GrindScreen_tempTarget, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GrindScreen_tempTarget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_GrindScreen_tempTarget, 300);
    ui_object_set_themeable_style_property(ui_GrindScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_GrindScreen_tempGauge = lv_arc_create(ui_GrindScreen);
    lv_obj_set_width(ui_GrindScreen_tempGauge, 480);
    lv_obj_set_height(ui_GrindScreen_tempGauge, 480);
    lv_obj_set_align(ui_GrindScreen_tempGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_GrindScreen_tempGauge, LV_STATE_DISABLED);       /// States
    lv_arc_set_range(ui_GrindScreen_tempGauge, 0, 160);
    lv_arc_set_value(ui_GrindScreen_tempGauge, 91);
    lv_arc_set_bg_angles(ui_GrindScreen_tempGauge, 112, 68);
    lv_obj_set_style_arc_width(ui_GrindScreen_tempGauge, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GrindScreen_tempGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_GrindScreen_tempGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_GrindScreen_tempGauge, 35, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_GrindScreen_tempGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_GrindScreen_tempGauge, &ui_img_489054950, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GrindScreen_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GrindScreen_tempGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_GrindScreen_ImgButton2 = lv_imgbtn_create(ui_GrindScreen);
    lv_imgbtn_set_src(ui_GrindScreen_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_GrindScreen_ImgButton2, 40);
    lv_obj_set_height(ui_GrindScreen_ImgButton2, 40);
    lv_obj_set_x(ui_GrindScreen_ImgButton2, 0);
    lv_obj_set_y(ui_GrindScreen_ImgButton2, 210);
    lv_obj_set_align(ui_GrindScreen_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_GrindScreen_ImgButton2, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_GrindScreen_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrindScreen_contentPanel7 = lv_obj_create(ui_GrindScreen);
    lv_obj_set_width(ui_GrindScreen_contentPanel7, 360);
    lv_obj_set_height(ui_GrindScreen_contentPanel7, 360);
    lv_obj_set_align(ui_GrindScreen_contentPanel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GrindScreen_contentPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GrindScreen_contentPanel7, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Transparent);
    ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Transparent);
    ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel7, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel7, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_OPA, _ui_theme_alpha_NiceWhite);

    ui_GrindScreen_mainLabel7 = lv_label_create(ui_GrindScreen_contentPanel7);
    lv_obj_set_width(ui_GrindScreen_mainLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GrindScreen_mainLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GrindScreen_mainLabel7, 0);
    lv_obj_set_y(ui_GrindScreen_mainLabel7, -140);
    lv_obj_set_align(ui_GrindScreen_mainLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GrindScreen_mainLabel7, "Grind");
    ui_object_set_themeable_style_property(ui_GrindScreen_mainLabel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_mainLabel7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_GrindScreen_mainLabel7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrindScreen_targetPressureHelp1 = lv_label_create(ui_GrindScreen_contentPanel7);
    lv_obj_set_width(ui_GrindScreen_targetPressureHelp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GrindScreen_targetPressureHelp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GrindScreen_targetPressureHelp1, 0);
    lv_obj_set_y(ui_GrindScreen_targetPressureHelp1, -80);
    lv_obj_set_align(ui_GrindScreen_targetPressureHelp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GrindScreen_targetPressureHelp1, "Target Duration");
    ui_object_set_themeable_style_property(ui_GrindScreen_targetPressureHelp1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_targetPressureHelp1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_GrindScreen_targetPressureHelp1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrindScreen_startButton = lv_imgbtn_create(ui_GrindScreen_contentPanel7);
    lv_imgbtn_set_src(ui_GrindScreen_startButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_445946954, NULL);
    lv_obj_set_width(ui_GrindScreen_startButton, 40);
    lv_obj_set_height(ui_GrindScreen_startButton, 40);
    lv_obj_set_x(ui_GrindScreen_startButton, 0);
    lv_obj_set_y(ui_GrindScreen_startButton, 110);
    lv_obj_set_align(ui_GrindScreen_startButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_GrindScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_GrindScreen_downDurationButton = lv_imgbtn_create(ui_GrindScreen_contentPanel7);
    lv_imgbtn_set_src(ui_GrindScreen_downDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1829139226, NULL);
    lv_obj_set_width(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_height(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_x(ui_GrindScreen_downDurationButton, 0);
    lv_obj_set_y(ui_GrindScreen_downDurationButton, 40);
    lv_obj_set_align(ui_GrindScreen_downDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_GrindScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_GrindScreen_upDurationButton = lv_imgbtn_create(ui_GrindScreen_contentPanel7);
    lv_imgbtn_set_src(ui_GrindScreen_upDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_height(ui_GrindScreen_upDurationButton, 40);
    lv_obj_set_x(ui_GrindScreen_upDurationButton, 0);
    lv_obj_set_y(ui_GrindScreen_upDurationButton, -40);
    lv_obj_set_align(ui_GrindScreen_upDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_GrindScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_GrindScreen_targetDuration = lv_label_create(ui_GrindScreen_contentPanel7);
    lv_obj_set_width(ui_GrindScreen_targetDuration, 60);
    lv_obj_set_height(ui_GrindScreen_targetDuration, 20);
    lv_obj_set_align(ui_GrindScreen_targetDuration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GrindScreen_targetDuration, "0:30");
    ui_object_set_themeable_style_property(ui_GrindScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_GrindScreen_targetDuration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GrindScreen_targetDuration, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GrindScreen_tempText = lv_label_create(ui_GrindScreen);
    lv_obj_set_width(ui_GrindScreen_tempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GrindScreen_tempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GrindScreen_tempText, 0);
    lv_obj_set_y(ui_GrindScreen_tempText, -180);
    lv_obj_set_align(ui_GrindScreen_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GrindScreen_tempText, "92°C");
    ui_object_set_themeable_style_property(ui_GrindScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_GrindScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_GrindScreen_tempText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_GrindScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_GrindScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_pad_left(ui_GrindScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_GrindScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_GrindScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_GrindScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GrindScreen_startButton, ui_event_GrindScreen_startButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GrindScreen_downDurationButton, ui_event_GrindScreen_downDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GrindScreen_upDurationButton, ui_event_GrindScreen_upDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GrindScreen, ui_event_GrindScreen, LV_EVENT_ALL, NULL);

}
