// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

void ui_GrindScreen_screen_init(void)
{
ui_GrindScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_GrindScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_GrindScreen, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_tempGauge4 = lv_arc_create(ui_GrindScreen);
lv_obj_set_width( ui_GrindScreen_tempGauge4, 440);
lv_obj_set_height( ui_GrindScreen_tempGauge4, 440);
lv_obj_set_align( ui_GrindScreen_tempGauge4, LV_ALIGN_CENTER );
lv_arc_set_range(ui_GrindScreen_tempGauge4, 0,145);
lv_arc_set_value(ui_GrindScreen_tempGauge4, 92);
lv_arc_set_bg_angles(ui_GrindScreen_tempGauge4,110,70);
lv_obj_set_style_arc_width(ui_GrindScreen_tempGauge4, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_GrindScreen_tempGauge4, lv_color_hex(0xFF4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindScreen_tempGauge4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindScreen_tempGauge4, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_GrindScreen_tempGauge4, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindScreen_tempGauge4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindScreen_tempTargetBrew2 = lv_arc_create(ui_GrindScreen);
lv_obj_set_width( ui_GrindScreen_tempTargetBrew2, 440);
lv_obj_set_height( ui_GrindScreen_tempTargetBrew2, 440);
lv_obj_set_align( ui_GrindScreen_tempTargetBrew2, LV_ALIGN_CENTER );
lv_arc_set_range(ui_GrindScreen_tempTargetBrew2, 0,145);
lv_arc_set_value(ui_GrindScreen_tempTargetBrew2, 110);
lv_arc_set_bg_angles(ui_GrindScreen_tempTargetBrew2,110,70);
lv_obj_set_style_bg_color(ui_GrindScreen_tempTargetBrew2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindScreen_tempTargetBrew2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindScreen_tempTargetBrew2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindScreen_tempTargetBrew2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindScreen_tempTargetBrew2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_GrindScreen_tempTargetBrew2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindScreen_tempTargetBrew2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_GrindScreen_tempTargetBrew2, lv_color_hex(0xFF4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_GrindScreen_tempTargetBrew2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_GrindScreen_tempTargetBrew2, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_GrindScreen_tempTargetBrew2, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GrindScreen_tempTargetBrew2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_GrindScreen_ImgButton4 = lv_imgbtn_create(ui_GrindScreen);
lv_imgbtn_set_src(ui_GrindScreen_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1895594966, NULL);
lv_obj_set_width( ui_GrindScreen_ImgButton4, 40);
lv_obj_set_height( ui_GrindScreen_ImgButton4, 40);
lv_obj_set_x( ui_GrindScreen_ImgButton4, 0 );
lv_obj_set_y( ui_GrindScreen_ImgButton4, 210 );
lv_obj_set_align( ui_GrindScreen_ImgButton4, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_GrindScreen_ImgButton4, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_GrindScreen_ImgButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_tempText7 = lv_label_create(ui_GrindScreen);
lv_obj_set_width( ui_GrindScreen_tempText7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindScreen_tempText7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrindScreen_tempText7, 0 );
lv_obj_set_y( ui_GrindScreen_tempText7, -196 );
lv_obj_set_align( ui_GrindScreen_tempText7, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrindScreen_tempText7,"92°C");
lv_obj_set_style_text_color(ui_GrindScreen_tempText7, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GrindScreen_tempText7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_GrindScreen_tempText7, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_contentPanel3 = lv_obj_create(ui_GrindScreen);
lv_obj_set_width( ui_GrindScreen_contentPanel3, 360);
lv_obj_set_height( ui_GrindScreen_contentPanel3, 360);
lv_obj_set_align( ui_GrindScreen_contentPanel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_GrindScreen_contentPanel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_GrindScreen_contentPanel3, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Transparent);
ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Transparent);
ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_contentPanel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_NiceWhite);

ui_GrindScreen_mainLabel2 = lv_label_create(ui_GrindScreen_contentPanel3);
lv_obj_set_width( ui_GrindScreen_mainLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindScreen_mainLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrindScreen_mainLabel2, 0 );
lv_obj_set_y( ui_GrindScreen_mainLabel2, -160 );
lv_obj_set_align( ui_GrindScreen_mainLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrindScreen_mainLabel2,"Grind");
ui_object_set_themeable_style_property(ui_GrindScreen_mainLabel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_mainLabel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_GrindScreen_mainLabel2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_Bar2 = lv_bar_create(ui_GrindScreen_contentPanel3);
lv_bar_set_range(ui_GrindScreen_Bar2, 0,18);
lv_bar_set_value(ui_GrindScreen_Bar2,5,LV_ANIM_OFF);
lv_bar_set_start_value(ui_GrindScreen_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_GrindScreen_Bar2, 180);
lv_obj_set_height( ui_GrindScreen_Bar2, 10);
lv_obj_set_x( ui_GrindScreen_Bar2, 0 );
lv_obj_set_y( ui_GrindScreen_Bar2, 80 );
lv_obj_set_align( ui_GrindScreen_Bar2, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Transparent);
ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Transparent);
ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_outline_width(ui_GrindScreen_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_GrindScreen_Bar2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_Bar2, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_NiceWhite);

ui_GrindScreen_progressLabel1 = lv_label_create(ui_GrindScreen_contentPanel3);
lv_obj_set_width( ui_GrindScreen_progressLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindScreen_progressLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrindScreen_progressLabel1, 0 );
lv_obj_set_y( ui_GrindScreen_progressLabel1, 115 );
lv_obj_set_align( ui_GrindScreen_progressLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrindScreen_progressLabel1,"5 / 18 g");
ui_object_set_themeable_style_property(ui_GrindScreen_progressLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_progressLabel1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);

ui_GrindScreen_selectedProfile1 = lv_label_create(ui_GrindScreen_contentPanel3);
lv_obj_set_width( ui_GrindScreen_selectedProfile1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindScreen_selectedProfile1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrindScreen_selectedProfile1, 0 );
lv_obj_set_y( ui_GrindScreen_selectedProfile1, -80 );
lv_obj_set_align( ui_GrindScreen_selectedProfile1, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrindScreen_selectedProfile1,"IUIUIU Classic");
ui_object_set_themeable_style_property(ui_GrindScreen_selectedProfile1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_selectedProfile1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_GrindScreen_selectedProfile1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_targetPressureHelp3 = lv_label_create(ui_GrindScreen_contentPanel3);
lv_obj_set_width( ui_GrindScreen_targetPressureHelp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GrindScreen_targetPressureHelp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GrindScreen_targetPressureHelp3, 0 );
lv_obj_set_y( ui_GrindScreen_targetPressureHelp3, -120 );
lv_obj_set_align( ui_GrindScreen_targetPressureHelp3, LV_ALIGN_CENTER );
lv_label_set_text(ui_GrindScreen_targetPressureHelp3,"Selected profile");
ui_object_set_themeable_style_property(ui_GrindScreen_targetPressureHelp3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_GrindScreen_targetPressureHelp3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_GrindScreen_targetPressureHelp3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_pauseButton1 = lv_imgbtn_create(ui_GrindScreen_contentPanel3);
lv_imgbtn_set_src(ui_GrindScreen_pauseButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_646127855, NULL);
lv_obj_set_width( ui_GrindScreen_pauseButton1, 40);
lv_obj_set_height( ui_GrindScreen_pauseButton1, 40);
lv_obj_set_x( ui_GrindScreen_pauseButton1, 50 );
lv_obj_set_y( ui_GrindScreen_pauseButton1, 0 );
lv_obj_set_align( ui_GrindScreen_pauseButton1, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_GrindScreen_pauseButton1, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_GrindScreen_pauseButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GrindScreen_tareButton1 = lv_imgbtn_create(ui_GrindScreen_contentPanel3);
lv_imgbtn_set_src(ui_GrindScreen_tareButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1138440778, NULL);
lv_obj_set_width( ui_GrindScreen_tareButton1, 40);
lv_obj_set_height( ui_GrindScreen_tareButton1, 40);
lv_obj_set_x( ui_GrindScreen_tareButton1, -50 );
lv_obj_set_y( ui_GrindScreen_tareButton1, 0 );
lv_obj_set_align( ui_GrindScreen_tareButton1, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_GrindScreen_tareButton1, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_GrindScreen_tareButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_GrindScreen, ui_event_GrindScreen, LV_EVENT_ALL, NULL);

}
