// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#include "../ui.h"

void ui_SteamScreen_screen_init(void)
{
ui_SteamScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SteamScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SteamScreen, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SteamScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_tempGauge = lv_arc_create(ui_SteamScreen);
lv_obj_set_width( ui_SteamScreen_tempGauge, 440);
lv_obj_set_height( ui_SteamScreen_tempGauge, 440);
lv_obj_set_align( ui_SteamScreen_tempGauge, LV_ALIGN_CENTER );
lv_arc_set_range(ui_SteamScreen_tempGauge, 0,145);
lv_arc_set_value(ui_SteamScreen_tempGauge, 92);
lv_arc_set_bg_angles(ui_SteamScreen_tempGauge,110,70);
lv_obj_set_style_arc_width(ui_SteamScreen_tempGauge, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SteamScreen_tempGauge, lv_color_hex(0xFF4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SteamScreen_tempGauge, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SteamScreen_tempGauge, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SteamScreen_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SteamScreen_tempGauge, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SteamScreen_tempTarget = lv_arc_create(ui_SteamScreen);
lv_obj_set_width( ui_SteamScreen_tempTarget, 440);
lv_obj_set_height( ui_SteamScreen_tempTarget, 440);
lv_obj_set_align( ui_SteamScreen_tempTarget, LV_ALIGN_CENTER );
lv_arc_set_range(ui_SteamScreen_tempTarget, 0,145);
lv_arc_set_value(ui_SteamScreen_tempTarget, 110);
lv_arc_set_bg_angles(ui_SteamScreen_tempTarget,110,70);
lv_obj_set_style_bg_color(ui_SteamScreen_tempTarget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SteamScreen_tempTarget, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_SteamScreen_tempTarget, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SteamScreen_tempTarget, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SteamScreen_tempTarget, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SteamScreen_tempTarget, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SteamScreen_tempTarget, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_SteamScreen_tempTarget, lv_color_hex(0xFF4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SteamScreen_tempTarget, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SteamScreen_tempTarget, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SteamScreen_tempTarget, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SteamScreen_tempTarget, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SteamScreen_ImgButton6 = lv_imgbtn_create(ui_SteamScreen);
lv_imgbtn_set_src(ui_SteamScreen_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1895594966, NULL);
lv_obj_set_width( ui_SteamScreen_ImgButton6, 40);
lv_obj_set_height( ui_SteamScreen_ImgButton6, 40);
lv_obj_set_x( ui_SteamScreen_ImgButton6, 0 );
lv_obj_set_y( ui_SteamScreen_ImgButton6, 210 );
lv_obj_set_align( ui_SteamScreen_ImgButton6, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_SteamScreen_ImgButton6, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_SteamScreen_ImgButton6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_tempText4 = lv_label_create(ui_SteamScreen);
lv_obj_set_width( ui_SteamScreen_tempText4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SteamScreen_tempText4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SteamScreen_tempText4, 0 );
lv_obj_set_y( ui_SteamScreen_tempText4, -196 );
lv_obj_set_align( ui_SteamScreen_tempText4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SteamScreen_tempText4,"92°C");
lv_obj_set_style_text_color(ui_SteamScreen_tempText4, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SteamScreen_tempText4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SteamScreen_tempText4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_contentPanel5 = lv_obj_create(ui_SteamScreen);
lv_obj_set_width( ui_SteamScreen_contentPanel5, 360);
lv_obj_set_height( ui_SteamScreen_contentPanel5, 360);
lv_obj_set_align( ui_SteamScreen_contentPanel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SteamScreen_contentPanel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SteamScreen_contentPanel5, 180, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Transparent);
ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Transparent);
ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_NiceWhite);

ui_SteamScreen_mainLabel5 = lv_label_create(ui_SteamScreen_contentPanel5);
lv_obj_set_width( ui_SteamScreen_mainLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SteamScreen_mainLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SteamScreen_mainLabel5, 0 );
lv_obj_set_y( ui_SteamScreen_mainLabel5, -160 );
lv_obj_set_align( ui_SteamScreen_mainLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_SteamScreen_mainLabel5,"Steam");
ui_object_set_themeable_style_property(ui_SteamScreen_mainLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_SteamScreen_mainLabel5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_SteamScreen_mainLabel5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_targetTempHelp2 = lv_label_create(ui_SteamScreen_contentPanel5);
lv_obj_set_width( ui_SteamScreen_targetTempHelp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SteamScreen_targetTempHelp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SteamScreen_targetTempHelp2, 0 );
lv_obj_set_y( ui_SteamScreen_targetTempHelp2, -80 );
lv_obj_set_align( ui_SteamScreen_targetTempHelp2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SteamScreen_targetTempHelp2,"Target Temperature");
ui_object_set_themeable_style_property(ui_SteamScreen_targetTempHelp2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_SteamScreen_targetTempHelp2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_SteamScreen_targetTempHelp2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_goButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
lv_imgbtn_set_src(ui_SteamScreen_goButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2106667244, NULL);
lv_obj_set_width( ui_SteamScreen_goButton, 40);
lv_obj_set_height( ui_SteamScreen_goButton, 40);
lv_obj_set_x( ui_SteamScreen_goButton, 0 );
lv_obj_set_y( ui_SteamScreen_goButton, 110 );
lv_obj_set_align( ui_SteamScreen_goButton, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_SteamScreen_goButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_SteamScreen_goButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_downTempButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
lv_imgbtn_set_src(ui_SteamScreen_downTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_980971367, NULL);
lv_obj_set_width( ui_SteamScreen_downTempButton, 40);
lv_obj_set_height( ui_SteamScreen_downTempButton, 40);
lv_obj_set_x( ui_SteamScreen_downTempButton, 0 );
lv_obj_set_y( ui_SteamScreen_downTempButton, 40 );
lv_obj_set_align( ui_SteamScreen_downTempButton, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_SteamScreen_downTempButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_SteamScreen_downTempButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_upTempButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
lv_imgbtn_set_src(ui_SteamScreen_upTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1895594966, NULL);
lv_obj_set_width( ui_SteamScreen_upTempButton, 40);
lv_obj_set_height( ui_SteamScreen_upTempButton, 40);
lv_obj_set_x( ui_SteamScreen_upTempButton, 0 );
lv_obj_set_y( ui_SteamScreen_upTempButton, -40 );
lv_obj_set_align( ui_SteamScreen_upTempButton, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_SteamScreen_upTempButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_SteamScreen_upTempButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SteamScreen_targetTemp = lv_label_create(ui_SteamScreen_contentPanel5);
lv_obj_set_width( ui_SteamScreen_targetTemp, 60);
lv_obj_set_height( ui_SteamScreen_targetTemp, 20);
lv_obj_set_align( ui_SteamScreen_targetTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_SteamScreen_targetTemp,"93°C");
ui_object_set_themeable_style_property(ui_SteamScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_SteamScreen_targetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_align(ui_SteamScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SteamScreen_targetTemp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SteamScreen_goButton, ui_event_SteamScreen_goButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SteamScreen_downTempButton, ui_event_SteamScreen_downTempButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SteamScreen_upTempButton, ui_event_SteamScreen_upTempButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SteamScreen, ui_event_SteamScreen, LV_EVENT_ALL, NULL);

}
