// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#ifndef _GAGGIUINO_UI_H
#define _GAGGIUINO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
void ui_event_InitScreen( lv_event_t * e);
extern lv_obj_t *ui_InitScreen;
extern lv_obj_t *ui_InitScreen_Image2;
extern lv_obj_t *ui_InitScreen_Label3;
// SCREEN: ui_ProfileScreen
void ui_ProfileScreen_screen_init(void);
void ui_event_ProfileScreen( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen;
extern lv_obj_t *ui_ProfileScreen_tempGauge;
extern lv_obj_t *ui_ProfileScreen_tempTarget;
extern lv_obj_t *ui_ProfileScreen_ImgButton1;
extern lv_obj_t *ui_ProfileScreen_tempText;
extern lv_obj_t *ui_ProfileScreen_contentPanel;
extern lv_obj_t *ui_ProfileScreen_mainLabel;
void ui_event_ProfileScreen_profileChoices( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_profileChoices;
// SCREEN: ui_MenuScreen
void ui_MenuScreen_screen_init(void);
extern lv_obj_t *ui_MenuScreen;
extern lv_obj_t *ui_MenuScreen_tempGauge;
extern lv_obj_t *ui_MenuScreen_tempTarget;
extern lv_obj_t *ui_MenuScreen_tempText;
extern lv_obj_t *ui_MenuScreen_contentPanel1;
extern lv_obj_t *ui_MenuScreen_grindButton1;
void ui_event_MenuScreen_brewButton1( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_brewButton1;
void ui_event_MenuScreen_profileButton1( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_profileButton1;
void ui_event_MenuScreen_extrasButton1( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_extrasButton1;
extern lv_obj_t *ui_MenuScreen_mainLabel4;
void ui_event_MenuScreen_standbyButton( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_standbyButton;
// SCREEN: ui_StatusScreen
void ui_StatusScreen_screen_init(void);
void ui_event_StatusScreen( lv_event_t * e);
extern lv_obj_t *ui_StatusScreen;
extern lv_obj_t *ui_StatusScreen_tempGauge;
extern lv_obj_t *ui_StatusScreen_tempTarget;
extern lv_obj_t *ui_StatusScreen_ImgButton3;
extern lv_obj_t *ui_StatusScreen_tempText;
extern lv_obj_t *ui_StatusScreen_contentPanel2;
extern lv_obj_t *ui_StatusScreen_mainLabel1;
extern lv_obj_t *ui_StatusScreen_progressBar;
extern lv_obj_t *ui_StatusScreen_progressLabel;
extern lv_obj_t *ui_StatusScreen_targetTempHelp;
extern lv_obj_t *ui_StatusScreen_targetDurationHelp;
extern lv_obj_t *ui_StatusScreen_targetDuration;
extern lv_obj_t *ui_StatusScreen_targetTemp;
void ui_event_StatusScreen_pauseButton( lv_event_t * e);
extern lv_obj_t *ui_StatusScreen_pauseButton;
// SCREEN: ui_GrindScreen
void ui_GrindScreen_screen_init(void);
void ui_event_GrindScreen( lv_event_t * e);
extern lv_obj_t *ui_GrindScreen;
extern lv_obj_t *ui_GrindScreen_tempGauge4;
extern lv_obj_t *ui_GrindScreen_tempTargetBrew2;
extern lv_obj_t *ui_GrindScreen_ImgButton4;
extern lv_obj_t *ui_GrindScreen_tempText7;
extern lv_obj_t *ui_GrindScreen_contentPanel3;
extern lv_obj_t *ui_GrindScreen_mainLabel2;
extern lv_obj_t *ui_GrindScreen_Bar2;
extern lv_obj_t *ui_GrindScreen_progressLabel1;
extern lv_obj_t *ui_GrindScreen_selectedProfile1;
extern lv_obj_t *ui_GrindScreen_targetPressureHelp3;
extern lv_obj_t *ui_GrindScreen_pauseButton1;
extern lv_obj_t *ui_GrindScreen_tareButton1;
// SCREEN: ui_BrewScreen
void ui_BrewScreen_screen_init(void);
void ui_event_BrewScreen( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen;
extern lv_obj_t *ui_BrewScreen_tempGauge;
extern lv_obj_t *ui_BrewScreen_tempTarget;
extern lv_obj_t *ui_BrewScreen_ImgButton5;
extern lv_obj_t *ui_BrewScreen_tempText;
extern lv_obj_t *ui_BrewScreen_contentPanel4;
extern lv_obj_t *ui_BrewScreen_mainLabel3;
extern lv_obj_t *ui_BrewScreen_targetTempHelp1;
extern lv_obj_t *ui_BrewScreen_targetPressureHelp2;
void ui_event_BrewScreen_startButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_startButton;
void ui_event_BrewScreen_downTempButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_downTempButton;
void ui_event_BrewScreen_upTempButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_upTempButton;
void ui_event_BrewScreen_downDurationButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_downDurationButton;
void ui_event_BrewScreen_upDurationButton( lv_event_t * e);
extern lv_obj_t *ui_BrewScreen_upDurationButton;
extern lv_obj_t *ui_BrewScreen_targetTemp;
extern lv_obj_t *ui_BrewScreen_targetDuration;
// SCREEN: ui_SteamScreen
void ui_SteamScreen_screen_init(void);
void ui_event_SteamScreen( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen;
extern lv_obj_t *ui_SteamScreen_tempGauge;
extern lv_obj_t *ui_SteamScreen_tempTarget;
extern lv_obj_t *ui_SteamScreen_ImgButton6;
extern lv_obj_t *ui_SteamScreen_tempText;
extern lv_obj_t *ui_SteamScreen_contentPanel5;
extern lv_obj_t *ui_SteamScreen_mainLabel5;
extern lv_obj_t *ui_SteamScreen_targetTempHelp2;
void ui_event_SteamScreen_goButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_goButton;
void ui_event_SteamScreen_downTempButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_downTempButton;
void ui_event_SteamScreen_upTempButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_upTempButton;
extern lv_obj_t *ui_SteamScreen_targetTemp;
// SCREEN: ui_WaterScreen
void ui_WaterScreen_screen_init(void);
void ui_event_WaterScreen( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen;
extern lv_obj_t *ui_WaterScreen_tempGauge;
extern lv_obj_t *ui_WaterScreen_tempTarget;
extern lv_obj_t *ui_WaterScreen_ImgButton7;
extern lv_obj_t *ui_WaterScreen_tempText;
extern lv_obj_t *ui_WaterScreen_contentPanel6;
extern lv_obj_t *ui_WaterScreen_mainLabel6;
extern lv_obj_t *ui_WaterScreen_targetTempHelp3;
void ui_event_WaterScreen_goButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_goButton;
void ui_event_WaterScreen_downTempButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_downTempButton;
void ui_event_WaterScreen_upTempButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_upTempButton;
extern lv_obj_t *ui_WaterScreen_targetTemp;
// SCREEN: ui_StandbyScreen
void ui_StandbyScreen_screen_init(void);
void ui_event_StandbyScreen( lv_event_t * e);
extern lv_obj_t *ui_StandbyScreen;
extern lv_obj_t *ui_StandbyScreen_Image1;
extern lv_obj_t *ui_StandbyScreen_text1;
extern lv_obj_t *ui_StandbyScreen_time;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1640786209);   // assets/gaggia-logo.png
LV_IMG_DECLARE( ui_img_1895594966);   // assets/chevron-up-solid (1).png
LV_IMG_DECLARE( ui_img_1857452635);   // assets/coffee-beans.png
LV_IMG_DECLARE( ui_img_753040508);   // assets/coffee-cup.png
LV_IMG_DECLARE( ui_img_2100879889);   // assets/water-80.png
LV_IMG_DECLARE( ui_img_2056842146);   // assets/steam-80.png
LV_IMG_DECLARE( ui_img_standby_png);   // assets/standby.png
LV_IMG_DECLARE( ui_img_646127855);   // assets/pause-solid.png
LV_IMG_DECLARE( ui_img_1138440778);   // assets/weight-hanging-solid.png
LV_IMG_DECLARE( ui_img_2106667244);   // assets/play-40.png
LV_IMG_DECLARE( ui_img_980971367);   // assets/chevron-down-solid.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
