// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#include "ui.h"
#include "../main.h"

extern int targetBrewTemp;
extern int targetSteamTemp;
extern int targetWaterTemp;
extern int mode;
extern void setBrewTemp(int temp);
extern void setSteamTemp(int temp);
extern void setTargetWaterTemp(int temp);
extern void setMode(int mode);

void onBrewCancel(lv_event_t * e)
{
	// Your code here
}

void onBrewStart(lv_event_t * e)
{
	// Your code here
}

void onBrewTempLower(lv_event_t * e)
{
  setBrewTemp(targetBrewTemp - 1);
}

void onBrewTempRaise(lv_event_t * e)
{
  setBrewTemp(targetBrewTemp + 1);
}

void onBrewTimeLower(lv_event_t * e)
{
	// Your code here
}

void onBrewTimeRaise(lv_event_t * e)
{
	// Your code here
}

void onSteamToggle(lv_event_t * e)
{
	// Your code here
}

void onSteamTempLower(lv_event_t * e)
{
  setSteamTemp(targetSteamTemp - 1);
}

void onSteamTempRaise(lv_event_t * e)
{
  setSteamTemp(targetSteamTemp + 1);
}

void onBrewScreen(lv_event_t * e)
{
  setMode(MODE_BREW);
}

void onWaterScreen(lv_event_t * e)
{
  setMode(MODE_WATER);
}

void onSteamScreen(lv_event_t * e)
{
  setMode(MODE_STEAM);
}

void onWaterToggle(lv_event_t * e)
{
	// Your code here
}

void onWakeup(lv_event_t * e)
{
  setMode(MODE_BREW);
}
