// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#include <Arduino.h>
#include "ui.h"
#include "../main.h"

extern int targetBrewTemp;
extern int targetSteamTemp;
extern int targetWaterTemp;
extern int targetDuration;
extern int mode;

void onBrewCancel(lv_event_t * e)
{
  deactivate();
}

void onBrewStart(lv_event_t * e)
{
  activate(millis() + targetDuration);
}

void onBrewTempLower(lv_event_t * e)
{
  setTargetBrewTemp(targetBrewTemp - 1);
}

void onBrewTempRaise(lv_event_t * e)
{
  setTargetBrewTemp(targetBrewTemp + 1);
}

void onBrewTimeLower(lv_event_t * e)
{
  int newDuration = targetDuration - 1000;
  if (newDuration < BREW_MIN_DURATION_MS) {
    newDuration = BREW_MIN_DURATION_MS;
  }
  setTargetDuration(newDuration);
}

void onBrewTimeRaise(lv_event_t * e)
{
  int newDuration = targetDuration + 1000;
  if (newDuration > BREW_MAX_DURATION_MS) {
    newDuration = BREW_MIN_DURATION_MS;
  }
  setTargetDuration(newDuration);
}

void onSteamToggle(lv_event_t * e)
{
  isActive() ? deactivate() : activate(millis() + STEAM_SAFETY_DURATION_MS);
}

void onSteamTempLower(lv_event_t * e)
{
  setTargetSteamTemp(targetSteamTemp - 1);
}

void onSteamTempRaise(lv_event_t * e)
{
  setTargetSteamTemp(targetSteamTemp + 1);
}

void onBrewScreen(lv_event_t * e)
{
  setMode(MODE_BREW);
  deactivate();
}

void onWaterScreen(lv_event_t * e)
{
  deactivate();
  setMode(MODE_WATER);
}

void onSteamScreen(lv_event_t * e)
{
  deactivate();
  setMode(MODE_STEAM);
}

void onWaterToggle(lv_event_t * e)
{
  isActive() ? deactivate() : activate(millis() + HOT_WATER_SAFETY_DURATION_MS);
}

void onWakeup(lv_event_t * e)
{
  deactivate();
  setMode(MODE_BREW);
}

void onWaterTempLower(lv_event_t * e)
{
  setTargetWaterTemp(targetWaterTemp - 1);
}

void onWaterTempRaise(lv_event_t * e)
{
  setTargetWaterTemp(targetWaterTemp + 1);
}

void onLoadStarted(lv_event_t * e)
{
  setupAfterScreen();
}
