// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#include "ui.h"

void onBrewCancel(lv_event_t * e)
{
	// Your code here
}

void onBrewStart(lv_event_t * e)
{
	// Your code here
}

void onBrewTempLower(lv_event_t * e)
{
	// Your code here
}

void onBrewTempRaise(lv_event_t * e)
{
	// Your code here
}

void onBrewTimeLower(lv_event_t * e)
{
	// Your code here
}

void onBrewTimeRaise(lv_event_t * e)
{
	// Your code here
}

void onSteamToggle(lv_event_t * e)
{
	// Your code here
}

void onSteamTempLower(lv_event_t * e)
{
	// Your code here
}

void onSteamTempRaise(lv_event_t * e)
{
	// Your code here
}
