// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Gaggiuino

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_NiceWhite[1] = {0xFAFAFA};
const ui_theme_variable_t _ui_theme_alpha_NiceWhite[1] = {255};

const ui_theme_variable_t _ui_theme_color_Dark[1] = {0x131313};
const ui_theme_variable_t _ui_theme_alpha_Dark[1] = {255};

const ui_theme_variable_t _ui_theme_color_SemiDark[1] = {0x333333};
const ui_theme_variable_t _ui_theme_alpha_SemiDark[1] = {255};

const ui_theme_variable_t _ui_theme_color_Transparent[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Transparent[1] = {0};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

