// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_PIEBUTTON_H
#define _UI_COMP_PIEBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PieButton
#define UI_COMP_PIEBUTTON_PIEBUTTON 0
#define _UI_COMP_PIEBUTTON_NUM 1
lv_obj_t *ui_PieButton_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
