/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "comms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CoffeeMachine_TemperatureControl, CoffeeMachine_TemperatureControl, AUTO)


PB_BIND(CoffeeMachine_PinControl, CoffeeMachine_PinControl, AUTO)


PB_BIND(CoffeeMachine_TemperatureRead, CoffeeMachine_TemperatureRead, AUTO)


PB_BIND(CoffeeMachine_PinRead, CoffeeMachine_PinRead, AUTO)


PB_BIND(CoffeeMachine_PIDAutotune, CoffeeMachine_PIDAutotune, AUTO)


PB_BIND(CoffeeMachine_Ping, CoffeeMachine_Ping, AUTO)


PB_BIND(CoffeeMachine_Error, CoffeeMachine_Error, AUTO)


PB_BIND(CoffeeMachine_Command, CoffeeMachine_Command, AUTO)







