#!/usr/bin/env bash

npx tailwindcss -i ./web/style.css -o ./web/style.tailwind.css
html_content=$(npx inliner -i ./web/index.html)
{
  echo "// This is an autogenerated file. Please check the build instructions on how to generate it"
  echo "#pragma once"
  echo "#include <Arduino.h>"
  echo "const char index_html[] PROGMEM = R\"***("
  echo "$html_content"
  echo ")***\";"
} > ./src/display/html.h
