#!/usr/bin/env bash

npx tailwindcss -i ./web/style.css -o ./web/style.tailwind.css
index_html=$(npx inliner -i ./web/index.html)
settings_html=$(npx inliner -i ./web/settings.html)
{
  echo "// This is an autogenerated file. Please check the build instructions on how to generate it"
  echo "#pragma once"
  echo "#include <Arduino.h>"
  echo "const char index_html[] PROGMEM = R\"***("
  echo "$index_html"
  echo ")***\";"
  echo "const char settings_html[] PROGMEM = R\"***("
  echo "$index_html"
  echo ")***\";"
} > ./src/display/html.h
