// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

void ui_BrewScreen_screen_init(void) {
    ui_BrewScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BrewScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);

    ui_BrewScreen_tempTarget = lv_img_create(ui_BrewScreen);
    lv_img_set_src(ui_BrewScreen_tempTarget, &ui_img_indicator_png);
    lv_obj_set_width(ui_BrewScreen_tempTarget, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_tempTarget, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_BrewScreen_tempTarget, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_tempTarget, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_tempTarget, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(ui_BrewScreen_tempTarget, 300);
    ui_object_set_themeable_style_property(ui_BrewScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_tempGauge = lv_arc_create(ui_BrewScreen);
    lv_obj_set_width(ui_BrewScreen_tempGauge, 480);
    lv_obj_set_height(ui_BrewScreen_tempGauge, 480);
    lv_obj_set_align(ui_BrewScreen_tempGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_BrewScreen_tempGauge, LV_STATE_DISABLED); /// States
    lv_arc_set_range(ui_BrewScreen_tempGauge, 0, 160);
    lv_arc_set_value(ui_BrewScreen_tempGauge, 91);
    lv_arc_set_bg_angles(ui_BrewScreen_tempGauge, 112, 68);
    lv_obj_set_style_arc_width(ui_BrewScreen_tempGauge, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BrewScreen_tempGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_BrewScreen_tempGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_BrewScreen_tempGauge, 35, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BrewScreen_tempGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_BrewScreen_tempGauge, &ui_img_489054950, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrewScreen_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewScreen_tempGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrewScreen_ImgButton5 = lv_imgbtn_create(ui_BrewScreen);
    lv_imgbtn_set_src(ui_BrewScreen_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_BrewScreen_ImgButton5, 40);
    lv_obj_set_height(ui_BrewScreen_ImgButton5, 40);
    lv_obj_set_x(ui_BrewScreen_ImgButton5, 0);
    lv_obj_set_y(ui_BrewScreen_ImgButton5, 210);
    lv_obj_set_align(ui_BrewScreen_ImgButton5, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_BrewScreen_ImgButton5, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_BrewScreen_ImgButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_contentPanel4 = lv_obj_create(ui_BrewScreen);
    lv_obj_set_width(ui_BrewScreen_contentPanel4, 360);
    lv_obj_set_height(ui_BrewScreen_contentPanel4, 360);
    lv_obj_set_align(ui_BrewScreen_contentPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_contentPanel4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_BrewScreen_contentPanel4, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Transparent);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Transparent);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_mainLabel3 = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_mainLabel3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_mainLabel3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_mainLabel3, 0);
    lv_obj_set_y(ui_BrewScreen_mainLabel3, -140);
    lv_obj_set_align(ui_BrewScreen_mainLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_mainLabel3, "Brew");
    ui_object_set_themeable_style_property(ui_BrewScreen_mainLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_mainLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_mainLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_targetTempHelp1 = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_targetTempHelp1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_targetTempHelp1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_targetTempHelp1, 0);
    lv_obj_set_y(ui_BrewScreen_targetTempHelp1, -30);
    lv_obj_set_align(ui_BrewScreen_targetTempHelp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetTempHelp1, "Target Temperature");
    lv_obj_add_flag(ui_BrewScreen_targetTempHelp1, LV_OBJ_FLAG_HIDDEN); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTempHelp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTempHelp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_targetTempHelp1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_targetPressureHelp2 = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_targetPressureHelp2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_targetPressureHelp2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_targetPressureHelp2, 0);
    lv_obj_set_y(ui_BrewScreen_targetPressureHelp2, 40);
    lv_obj_set_align(ui_BrewScreen_targetPressureHelp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetPressureHelp2, "Target Duration");
    lv_obj_add_flag(ui_BrewScreen_targetPressureHelp2, LV_OBJ_FLAG_HIDDEN); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_targetPressureHelp2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetPressureHelp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_targetPressureHelp2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_startButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_startButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_445946954, NULL);
    lv_obj_set_width(ui_BrewScreen_startButton, 40);
    lv_obj_set_height(ui_BrewScreen_startButton, 40);
    lv_obj_set_x(ui_BrewScreen_startButton, 0);
    lv_obj_set_y(ui_BrewScreen_startButton, 120);
    lv_obj_set_align(ui_BrewScreen_startButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_outline_width(ui_BrewScreen_startButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BrewScreen_startButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_downTempButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_downTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_834125362, NULL);
    lv_obj_set_width(ui_BrewScreen_downTempButton, 40);
    lv_obj_set_height(ui_BrewScreen_downTempButton, 40);
    lv_obj_set_x(ui_BrewScreen_downTempButton, -60);
    lv_obj_set_y(ui_BrewScreen_downTempButton, -10);
    lv_obj_set_align(ui_BrewScreen_downTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_upTempButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_upTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_390988422, NULL);
    lv_obj_set_width(ui_BrewScreen_upTempButton, 40);
    lv_obj_set_height(ui_BrewScreen_upTempButton, 40);
    lv_obj_set_x(ui_BrewScreen_upTempButton, 120);
    lv_obj_set_y(ui_BrewScreen_upTempButton, -10);
    lv_obj_set_align(ui_BrewScreen_upTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_downDurationButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_downDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_834125362, NULL);
    lv_obj_set_width(ui_BrewScreen_downDurationButton, 40);
    lv_obj_set_height(ui_BrewScreen_downDurationButton, 40);
    lv_obj_set_x(ui_BrewScreen_downDurationButton, -60);
    lv_obj_set_y(ui_BrewScreen_downDurationButton, 50);
    lv_obj_set_align(ui_BrewScreen_downDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_upDurationButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_upDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_390988422, NULL);
    lv_obj_set_width(ui_BrewScreen_upDurationButton, 40);
    lv_obj_set_height(ui_BrewScreen_upDurationButton, 40);
    lv_obj_set_x(ui_BrewScreen_upDurationButton, 120);
    lv_obj_set_y(ui_BrewScreen_upDurationButton, 50);
    lv_obj_set_align(ui_BrewScreen_upDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_targetTemp = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_targetTemp, 90);
    lv_obj_set_height(ui_BrewScreen_targetTemp, 30);
    lv_obj_set_x(ui_BrewScreen_targetTemp, 30);
    lv_obj_set_y(ui_BrewScreen_targetTemp, -10);
    lv_obj_set_align(ui_BrewScreen_targetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetTemp, "93°C");
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_BrewScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_targetTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_targetDuration = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_targetDuration, 90);
    lv_obj_set_height(ui_BrewScreen_targetDuration, 30);
    lv_obj_set_x(ui_BrewScreen_targetDuration, 30);
    lv_obj_set_y(ui_BrewScreen_targetDuration, 50);
    lv_obj_set_align(ui_BrewScreen_targetDuration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetDuration, "0:30");
    ui_object_set_themeable_style_property(ui_BrewScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_BrewScreen_targetDuration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_targetDuration, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_Image4 = lv_img_create(ui_BrewScreen_contentPanel4);
    lv_img_set_src(ui_BrewScreen_Image4, &ui_img_360122106);
    lv_obj_set_width(ui_BrewScreen_Image4, 40);
    lv_obj_set_height(ui_BrewScreen_Image4, 40);
    lv_obj_set_x(ui_BrewScreen_Image4, -120);
    lv_obj_set_y(ui_BrewScreen_Image4, 50);
    lv_obj_set_align(ui_BrewScreen_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_Image4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_Image4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_Image4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_Image4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_Image5 = lv_img_create(ui_BrewScreen_contentPanel4);
    lv_img_set_src(ui_BrewScreen_Image5, &ui_img_1951499226);
    lv_obj_set_width(ui_BrewScreen_Image5, 40);
    lv_obj_set_height(ui_BrewScreen_Image5, 40);
    lv_obj_set_x(ui_BrewScreen_Image5, -120);
    lv_obj_set_y(ui_BrewScreen_Image5, -10);
    lv_obj_set_align(ui_BrewScreen_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_Image5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_Image5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_Image5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_Image5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_tempText = lv_label_create(ui_BrewScreen);
    lv_obj_set_width(ui_BrewScreen_tempText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_tempText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_tempText, 0);
    lv_obj_set_y(ui_BrewScreen_tempText, -180);
    lv_obj_set_align(ui_BrewScreen_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_tempText, "92°C");
    lv_obj_set_style_text_color(ui_BrewScreen_tempText, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrewScreen_tempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_tempText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_pad_left(ui_BrewScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrewScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrewScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrewScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_modeSwitch = lv_obj_create(ui_BrewScreen);
    lv_obj_remove_style_all(ui_BrewScreen_modeSwitch);
    lv_obj_set_width(ui_BrewScreen_modeSwitch, 160);
    lv_obj_set_height(ui_BrewScreen_modeSwitch, 50);
    lv_obj_set_x(ui_BrewScreen_modeSwitch, 0);
    lv_obj_set_y(ui_BrewScreen_modeSwitch, -90);
    lv_obj_set_align(ui_BrewScreen_modeSwitch, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_modeSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_BrewScreen_modeSwitch, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Dark);
    lv_obj_set_style_bg_main_stop(ui_BrewScreen_modeSwitch, 127, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BrewScreen_modeSwitch, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BrewScreen_modeSwitch, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_border_width(ui_BrewScreen_modeSwitch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BrewScreen_modeSwitch, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_timedButton = lv_btn_create(ui_BrewScreen_modeSwitch);
    lv_obj_set_width(ui_BrewScreen_timedButton, 80);
    lv_obj_set_height(ui_BrewScreen_timedButton, 50);
    lv_obj_set_x(ui_BrewScreen_timedButton, -40);
    lv_obj_set_y(ui_BrewScreen_timedButton, 0);
    lv_obj_set_align(ui_BrewScreen_timedButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_timedButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_BrewScreen_timedButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_BrewScreen_timedButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewScreen_timedButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewScreen_timedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BrewScreen_timedButton, &ui_img_360122106, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_timedButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen_timedButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_Dark);
    lv_obj_set_style_shadow_color(ui_BrewScreen_timedButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrewScreen_timedButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_volumetricButton = lv_btn_create(ui_BrewScreen_modeSwitch);
    lv_obj_set_width(ui_BrewScreen_volumetricButton, 80);
    lv_obj_set_height(ui_BrewScreen_volumetricButton, 50);
    lv_obj_set_x(ui_BrewScreen_volumetricButton, 40);
    lv_obj_set_y(ui_BrewScreen_volumetricButton, 0);
    lv_obj_set_align(ui_BrewScreen_volumetricButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_volumetricButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_BrewScreen_volumetricButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_BrewScreen_volumetricButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewScreen_volumetricButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BrewScreen_volumetricButton, &ui_img_1424216268, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_volumetricButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_volumetricButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_shadow_color(ui_BrewScreen_volumetricButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrewScreen_volumetricButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BrewScreen_startButton, ui_event_BrewScreen_startButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_downTempButton, ui_event_BrewScreen_downTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_upTempButton, ui_event_BrewScreen_upTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_downDurationButton, ui_event_BrewScreen_downDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_upDurationButton, ui_event_BrewScreen_upDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_timedButton, ui_event_BrewScreen_timedButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_volumetricButton, ui_event_BrewScreen_volumetricButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen, ui_event_BrewScreen, LV_EVENT_ALL, NULL);
}
