// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *ui_InitScreen = NULL;lv_obj_t *ui_InitScreen_Image10 = NULL;lv_obj_t *ui_InitScreen_mainLabel = NULL;
// event funtions
void ui_event_InitScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      onLoadStarted( e );
}
}

// build funtions

void ui_InitScreen_screen_init(void)
{
ui_InitScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_InitScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_event_cb(ui_InitScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_InitScreen_screen_destroy);
ui_object_set_themeable_style_property(ui_InitScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Dark);
ui_object_set_themeable_style_property(ui_InitScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);

ui_InitScreen_Image10 = lv_img_create(ui_InitScreen);
lv_img_set_src(ui_InitScreen_Image10, &ui_img_817656348);
lv_obj_set_width( ui_InitScreen_Image10, LV_SIZE_CONTENT);  /// 401
lv_obj_set_height( ui_InitScreen_Image10, LV_SIZE_CONTENT);   /// 105
lv_obj_set_align( ui_InitScreen_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InitScreen_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_InitScreen_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InitScreen_mainLabel = lv_label_create(ui_InitScreen);
lv_obj_set_width( ui_InitScreen_mainLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InitScreen_mainLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InitScreen_mainLabel, 0 );
lv_obj_set_y( ui_InitScreen_mainLabel, 150 );
lv_obj_set_align( ui_InitScreen_mainLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InitScreen_mainLabel,"");
ui_object_set_themeable_style_property(ui_InitScreen_mainLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_NiceWhite);
ui_object_set_themeable_style_property(ui_InitScreen_mainLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_NiceWhite);
lv_obj_set_style_text_font(ui_InitScreen_mainLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_InitScreen, ui_event_InitScreen, LV_EVENT_ALL, NULL);

}

void ui_InitScreen_screen_destroy(void)
{
   if (ui_InitScreen) lv_obj_del(ui_InitScreen);

// NULL screen variables
ui_InitScreen= NULL;
ui_InitScreen_Image10= NULL;
ui_InitScreen_mainLabel= NULL;

}
