// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_INITSCREEN_H
#define UI_INITSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InitScreen
extern void ui_InitScreen_screen_init(void);
extern void ui_InitScreen_screen_destroy(void);
extern void ui_event_InitScreen( lv_event_t * e);
extern lv_obj_t *ui_InitScreen;
extern lv_obj_t *ui_InitScreen_Image10;
extern lv_obj_t *ui_InitScreen_mainLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

