// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern void ui_event_MenuScreen( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen;
extern lv_obj_t *ui_MenuScreen_dials;
extern void ui_event_MenuScreen_standbyButton( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_standbyButton;
extern lv_obj_t *ui_MenuScreen_contentPanel1;
extern void ui_event_MenuScreen_btnBrew( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_btnBrew;
extern void ui_event_MenuScreen_btnSteam( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_btnSteam;
extern void ui_event_MenuScreen_waterBtn( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_waterBtn;
extern void ui_event_MenuScreen_grindBtn( lv_event_t * e);
extern lv_obj_t *ui_MenuScreen_grindBtn;
// CUSTOM VARIABLES
extern lv_obj_t *uic_MenuScreen_dials_tempGauge;
extern lv_obj_t *uic_MenuScreen_dials_tempTarget;
extern lv_obj_t *uic_MenuScreen_dials_pressureGauge;
extern lv_obj_t *uic_MenuScreen_dials_pressureTarget;
extern lv_obj_t *uic_MenuScreen_dials_pressureText;
extern lv_obj_t *uic_MenuScreen_dials_tempText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

