// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

void ui_MenuScreen_screen_init(void) {
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_MenuScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_MenuScreen);
    ui_object_set_themeable_style_property(ui_MenuScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_MenuScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);

    ui_MenuScreen_dials = ui_dials_create(ui_MenuScreen);
    lv_obj_set_x(ui_MenuScreen_dials, 0);
    lv_obj_set_y(ui_MenuScreen_dials, 0);

    ui_MenuScreen_standbyButton = lv_imgbtn_create(ui_MenuScreen);
    lv_imgbtn_set_src(ui_MenuScreen_standbyButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2044104741, NULL);
    lv_obj_set_width(ui_MenuScreen_standbyButton, 40);
    lv_obj_set_height(ui_MenuScreen_standbyButton, 40);
    lv_obj_set_x(ui_MenuScreen_standbyButton, 0);
    lv_obj_set_y(ui_MenuScreen_standbyButton, 210);
    lv_obj_set_align(ui_MenuScreen_standbyButton, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_MenuScreen_standbyButton, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MenuScreen_standbyButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MenuScreen_standbyButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MenuScreen_standbyButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_standbyButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_MenuScreen_standbyButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_MenuScreen_contentPanel1 = lv_obj_create(ui_MenuScreen);
    lv_obj_set_width(ui_MenuScreen_contentPanel1, 360);
    lv_obj_set_height(ui_MenuScreen_contentPanel1, 360);
    lv_obj_set_align(ui_MenuScreen_contentPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuScreen_contentPanel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_MenuScreen_contentPanel1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_MenuScreen_contentPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_MenuScreen_contentPanel1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MenuScreen_contentPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen_contentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MenuScreen_contentPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MenuScreen_contentPanel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuScreen_contentPanel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuScreen_contentPanel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuScreen_contentPanel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuScreen_btnBrew = lv_btn_create(ui_MenuScreen_contentPanel1);
    lv_obj_set_width(ui_MenuScreen_btnBrew, 120);
    lv_obj_set_height(ui_MenuScreen_btnBrew, 120);
    lv_obj_set_align(ui_MenuScreen_btnBrew, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuScreen_btnBrew, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_MenuScreen_btnBrew, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen_btnBrew, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen_btnBrew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MenuScreen_btnBrew, &ui_img_979979123, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnBrew, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnBrew, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_outline_color(ui_MenuScreen_btnBrew, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MenuScreen_btnBrew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MenuScreen_btnBrew, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MenuScreen_btnBrew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnBrew, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnBrew, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_shadow_width(ui_MenuScreen_btnBrew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MenuScreen_btnBrew, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuScreen_btnSteam = lv_btn_create(ui_MenuScreen_contentPanel1);
    lv_obj_set_width(ui_MenuScreen_btnSteam, 120);
    lv_obj_set_height(ui_MenuScreen_btnSteam, 120);
    lv_obj_set_align(ui_MenuScreen_btnSteam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuScreen_btnSteam, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_MenuScreen_btnSteam, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen_btnSteam, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen_btnSteam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MenuScreen_btnSteam, &ui_img_783005998, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnSteam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnSteam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_outline_color(ui_MenuScreen_btnSteam, lv_color_hex(0x1FFBA3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MenuScreen_btnSteam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MenuScreen_btnSteam, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MenuScreen_btnSteam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnSteam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_MenuScreen_btnSteam, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_shadow_width(ui_MenuScreen_btnSteam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MenuScreen_btnSteam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuScreen_waterBtn = lv_btn_create(ui_MenuScreen_contentPanel1);
    lv_obj_set_width(ui_MenuScreen_waterBtn, 120);
    lv_obj_set_height(ui_MenuScreen_waterBtn, 120);
    lv_obj_set_align(ui_MenuScreen_waterBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuScreen_waterBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_MenuScreen_waterBtn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen_waterBtn, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen_waterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MenuScreen_waterBtn, &ui_img_545340440, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_waterBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_MenuScreen_waterBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_outline_color(ui_MenuScreen_waterBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MenuScreen_waterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MenuScreen_waterBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MenuScreen_waterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_waterBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_MenuScreen_waterBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_shadow_width(ui_MenuScreen_waterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MenuScreen_waterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuScreen_grindBtn = lv_btn_create(ui_MenuScreen_contentPanel1);
    lv_obj_set_width(ui_MenuScreen_grindBtn, 120);
    lv_obj_set_height(ui_MenuScreen_grindBtn, 120);
    lv_obj_set_align(ui_MenuScreen_grindBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuScreen_grindBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_MenuScreen_grindBtn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen_grindBtn, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen_grindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MenuScreen_grindBtn, &ui_img_363557387, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_grindBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_MenuScreen_grindBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_outline_color(ui_MenuScreen_grindBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MenuScreen_grindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MenuScreen_grindBtn, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MenuScreen_grindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_MenuScreen_grindBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_MenuScreen_grindBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_SHADOW_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_shadow_width(ui_MenuScreen_grindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MenuScreen_grindBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuScreen_standbyButton, ui_event_MenuScreen_standbyButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuScreen_btnBrew, ui_event_MenuScreen_btnBrew, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuScreen_btnSteam, ui_event_MenuScreen_btnSteam, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuScreen_waterBtn, ui_event_MenuScreen_waterBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuScreen_grindBtn, ui_event_MenuScreen_grindBtn, LV_EVENT_ALL, NULL);
    uic_MenuScreen_dials_tempGauge = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
    uic_MenuScreen_dials_tempTarget = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_TEMPTARGET);
    uic_MenuScreen_dials_pressureGauge = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_PRESSUREGAUGE);
    uic_MenuScreen_dials_pressureTarget = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_PRESSURETARGET);
    uic_MenuScreen_dials_pressureText = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_PRESSURETEXT);
    uic_MenuScreen_dials_tempText = ui_comp_get_child(ui_MenuScreen_dials, UI_COMP_DIALS_TEMPTEXT);
}
