// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_PROFILESCREEN_H
#define UI_PROFILESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ProfileScreen
extern void ui_ProfileScreen_screen_init(void);
extern void ui_ProfileScreen_screen_destroy(void);
extern void ui_event_ProfileScreen( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen;
extern lv_obj_t *ui_ProfileScreen_dials;
extern void ui_event_ProfileScreen_ImgButton1( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_ImgButton1;
extern lv_obj_t *ui_ProfileScreen_contentPanel;
extern void ui_event_ProfileScreen_previousProfileBtn( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_previousProfileBtn;
extern void ui_event_ProfileScreen_nextProfileBtn( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_nextProfileBtn;
extern lv_obj_t *ui_ProfileScreen_loadingSpinner;
extern lv_obj_t *ui_ProfileScreen_profileDetails;
extern void ui_event_ProfileScreen_chooseButton( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_chooseButton;
extern lv_obj_t *ui_ProfileScreen_simpleContent;
extern lv_obj_t *ui_ProfileScreen_phasesLabel;
extern lv_obj_t *ui_ProfileScreen_stepsLabel;
extern lv_obj_t *ui_ProfileScreen_extendedContent;
extern lv_obj_t *ui_ProfileScreen_Chart1;
extern lv_obj_t *ui_ProfileScreen_mainLabel;
extern lv_obj_t *ui_ProfileScreen_profileName;
extern lv_obj_t *ui_ProfileScreen_tempIcon;
extern lv_obj_t *ui_ProfileScreen_targetIcon;
extern lv_obj_t *ui_ProfileScreen_targetTemp2;
extern lv_obj_t *ui_ProfileScreen_targetDuration2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ProfileScreen_dials_tempGauge;
extern lv_obj_t *uic_ProfileScreen_dials_tempTarget;
extern lv_obj_t *uic_ProfileScreen_dials_pressureGauge;
extern lv_obj_t *uic_ProfileScreen_dials_pressureTarget;
extern lv_obj_t *uic_ProfileScreen_dials_pressureText;
extern lv_obj_t *uic_ProfileScreen_dials_tempText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

