// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

void ui_SteamScreen_screen_init(void) {
    ui_SteamScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SteamScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_SteamScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SteamScreen);
    ui_object_set_themeable_style_property(ui_SteamScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_SteamScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    ui_SteamScreen_tempTarget = lv_img_create(ui_SteamScreen);
    lv_img_set_src(ui_SteamScreen_tempTarget, &ui_img_indicator_png);
    lv_obj_set_width(ui_SteamScreen_tempTarget, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SteamScreen_tempTarget, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SteamScreen_tempTarget, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SteamScreen_tempTarget, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SteamScreen_tempTarget, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(ui_SteamScreen_tempTarget, 300);
    ui_object_set_themeable_style_property(ui_SteamScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_SteamScreen_tempGauge = lv_arc_create(ui_SteamScreen);
    lv_obj_set_width(ui_SteamScreen_tempGauge, 480);
    lv_obj_set_height(ui_SteamScreen_tempGauge, 480);
    lv_obj_set_align(ui_SteamScreen_tempGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SteamScreen_tempGauge, LV_STATE_DISABLED); /// States
    lv_arc_set_range(ui_SteamScreen_tempGauge, 0, 160);
    lv_arc_set_value(ui_SteamScreen_tempGauge, 91);
    lv_arc_set_bg_angles(ui_SteamScreen_tempGauge, 112, 68);
    lv_obj_set_style_arc_width(ui_SteamScreen_tempGauge, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SteamScreen_tempGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_SteamScreen_tempGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_SteamScreen_tempGauge, 35, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SteamScreen_tempGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_SteamScreen_tempGauge, &ui_img_489054950, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SteamScreen_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SteamScreen_tempGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SteamScreen_ImgButton6 = lv_imgbtn_create(ui_SteamScreen);
    lv_imgbtn_set_src(ui_SteamScreen_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_SteamScreen_ImgButton6, 40);
    lv_obj_set_height(ui_SteamScreen_ImgButton6, 40);
    lv_obj_set_x(ui_SteamScreen_ImgButton6, 0);
    lv_obj_set_y(ui_SteamScreen_ImgButton6, 210);
    lv_obj_set_align(ui_SteamScreen_ImgButton6, LV_ALIGN_CENTER);
    lv_obj_set_style_img_recolor(ui_SteamScreen_ImgButton6, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_SteamScreen_ImgButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SteamScreen_contentPanel5 = lv_obj_create(ui_SteamScreen);
    lv_obj_set_width(ui_SteamScreen_contentPanel5, 360);
    lv_obj_set_height(ui_SteamScreen_contentPanel5, 360);
    lv_obj_set_align(ui_SteamScreen_contentPanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SteamScreen_contentPanel5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SteamScreen_contentPanel5, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Transparent);
    ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Transparent);
    ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_contentPanel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_SteamScreen_mainLabel5 = lv_label_create(ui_SteamScreen_contentPanel5);
    lv_obj_set_width(ui_SteamScreen_mainLabel5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SteamScreen_mainLabel5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SteamScreen_mainLabel5, 0);
    lv_obj_set_y(ui_SteamScreen_mainLabel5, -140);
    lv_obj_set_align(ui_SteamScreen_mainLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteamScreen_mainLabel5, "Steam");
    ui_object_set_themeable_style_property(ui_SteamScreen_mainLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_mainLabel5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_SteamScreen_mainLabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SteamScreen_targetTempHelp2 = lv_label_create(ui_SteamScreen_contentPanel5);
    lv_obj_set_width(ui_SteamScreen_targetTempHelp2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SteamScreen_targetTempHelp2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SteamScreen_targetTempHelp2, 0);
    lv_obj_set_y(ui_SteamScreen_targetTempHelp2, -80);
    lv_obj_set_align(ui_SteamScreen_targetTempHelp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteamScreen_targetTempHelp2, "Target Temperature");
    ui_object_set_themeable_style_property(ui_SteamScreen_targetTempHelp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_targetTempHelp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_SteamScreen_targetTempHelp2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SteamScreen_goButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
    lv_imgbtn_set_src(ui_SteamScreen_goButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_445946954, NULL);
    lv_obj_set_width(ui_SteamScreen_goButton, 40);
    lv_obj_set_height(ui_SteamScreen_goButton, 40);
    lv_obj_set_x(ui_SteamScreen_goButton, 0);
    lv_obj_set_y(ui_SteamScreen_goButton, 110);
    lv_obj_set_align(ui_SteamScreen_goButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_SteamScreen_goButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_SteamScreen_goButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_outline_width(ui_SteamScreen_goButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SteamScreen_goButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SteamScreen_goButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_goButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_SteamScreen_downTempButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
    lv_imgbtn_set_src(ui_SteamScreen_downTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1829139226, NULL);
    lv_obj_set_width(ui_SteamScreen_downTempButton, 40);
    lv_obj_set_height(ui_SteamScreen_downTempButton, 40);
    lv_obj_set_x(ui_SteamScreen_downTempButton, 0);
    lv_obj_set_y(ui_SteamScreen_downTempButton, 40);
    lv_obj_set_align(ui_SteamScreen_downTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_SteamScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_SteamScreen_upTempButton = lv_imgbtn_create(ui_SteamScreen_contentPanel5);
    lv_imgbtn_set_src(ui_SteamScreen_upTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_SteamScreen_upTempButton, 40);
    lv_obj_set_height(ui_SteamScreen_upTempButton, 40);
    lv_obj_set_x(ui_SteamScreen_upTempButton, 0);
    lv_obj_set_y(ui_SteamScreen_upTempButton, -40);
    lv_obj_set_align(ui_SteamScreen_upTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_SteamScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_SteamScreen_targetTemp = lv_label_create(ui_SteamScreen_contentPanel5);
    lv_obj_set_width(ui_SteamScreen_targetTemp, 60);
    lv_obj_set_height(ui_SteamScreen_targetTemp, 20);
    lv_obj_set_align(ui_SteamScreen_targetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteamScreen_targetTemp, "145°C");
    ui_object_set_themeable_style_property(ui_SteamScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_SteamScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SteamScreen_targetTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SteamScreen_tempText = lv_label_create(ui_SteamScreen);
    lv_obj_set_width(ui_SteamScreen_tempText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SteamScreen_tempText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SteamScreen_tempText, 0);
    lv_obj_set_y(ui_SteamScreen_tempText, -180);
    lv_obj_set_align(ui_SteamScreen_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteamScreen_tempText, "92°C");
    ui_object_set_themeable_style_property(ui_SteamScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_SteamScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_SteamScreen_tempText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_SteamScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_SteamScreen_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_pad_left(ui_SteamScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SteamScreen_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SteamScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SteamScreen_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SteamScreen_goButton, ui_event_SteamScreen_goButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SteamScreen_downTempButton, ui_event_SteamScreen_downTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SteamScreen_upTempButton, ui_event_SteamScreen_upTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SteamScreen, ui_event_SteamScreen, LV_EVENT_ALL, NULL);
}
