// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_COMP_DIALS_H
#define _UI_COMP_DIALS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dials
#define UI_COMP_DIALS_DIALS 0
#define UI_COMP_DIALS_TEMPGAUGE 1
#define UI_COMP_DIALS_TEMPTARGET 2
#define UI_COMP_DIALS_PRESSUREGAUGE 3
#define UI_COMP_DIALS_PRESSURETARGET 4
#define UI_COMP_DIALS_PRESSURETEXT 5
#define UI_COMP_DIALS_TEMPTEXT 6
#define UI_COMP_DIALS_TEMPICON 7
#define UI_COMP_DIALS_IMAGE6 8
#define _UI_COMP_DIALS_NUM 9
lv_obj_t *ui_dials_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
