// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

// COMPONENT dials

lv_obj_t *ui_dials_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_dials;
    cui_dials = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_dials);
    lv_obj_set_width(cui_dials, 480);
    lv_obj_set_height(cui_dials, 480);
    lv_obj_set_align(cui_dials, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_dials, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t *cui_tempTarget;
    cui_tempTarget = lv_img_create(cui_dials);
    lv_img_set_src(cui_tempTarget, &ui_img_indicator_png);
    lv_obj_set_width(cui_tempTarget, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_tempTarget, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_tempTarget, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_tempTarget, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(cui_tempTarget, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(cui_tempTarget, -900);
    ui_object_set_themeable_style_property(cui_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_tempTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    lv_obj_t *cui_tempGauge;
    cui_tempGauge = lv_arc_create(cui_dials);
    lv_obj_set_width(cui_tempGauge, 480);
    lv_obj_set_height(cui_tempGauge, 480);
    lv_obj_set_align(cui_tempGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_tempGauge, LV_STATE_DISABLED); /// States
    lv_arc_set_range(cui_tempGauge, 0, 160);
    lv_arc_set_value(cui_tempGauge, 80);
    lv_arc_set_bg_angles(cui_tempGauge, 118, 242);
    lv_obj_set_style_arc_width(cui_tempGauge, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_tempGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(cui_tempGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(cui_tempGauge, 35, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_tempGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(cui_tempGauge, &ui_img_489054950, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_tempGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_tempGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t *cui_pressureTarget;
    cui_pressureTarget = lv_img_create(cui_dials);
    lv_img_set_src(cui_pressureTarget, &ui_img_indicator_png);
    lv_obj_set_width(cui_pressureTarget, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_pressureTarget, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_pressureTarget, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_pressureTarget, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(cui_pressureTarget, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_angle(cui_pressureTarget, 900);
    ui_object_set_themeable_style_property(cui_pressureTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_pressureTarget, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    lv_obj_t *cui_pressureGauge;
    cui_pressureGauge = lv_arc_create(cui_dials);
    lv_obj_set_width(cui_pressureGauge, 480);
    lv_obj_set_height(cui_pressureGauge, 480);
    lv_obj_set_align(cui_pressureGauge, LV_ALIGN_CENTER);
    lv_obj_add_state(cui_pressureGauge, LV_STATE_DISABLED); /// States
    lv_arc_set_range(cui_pressureGauge, 0, 16);
    lv_arc_set_value(cui_pressureGauge, 8);
    lv_arc_set_bg_angles(cui_pressureGauge, 298, 62);
    lv_arc_set_mode(cui_pressureGauge, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_width(cui_pressureGauge, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_pressureGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(cui_pressureGauge, &ui_img_untitled_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(cui_pressureGauge, 35, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_pressureGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(cui_pressureGauge, &ui_img_1455708189, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_pressureGauge, lv_color_hex(0xD10000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_pressureGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t *cui_pressureText;
    cui_pressureText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_pressureText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_pressureText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(cui_pressureText, 50);
    lv_obj_set_y(cui_pressureText, -205);
    lv_obj_set_align(cui_pressureText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_pressureText, "9 bar");
    ui_object_set_themeable_style_property(cui_pressureText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_pressureText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(cui_pressureText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_pressureText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_pressureText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_pressureText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_pressureText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_tempText;
    cui_tempText = lv_label_create(cui_dials);
    lv_obj_set_width(cui_tempText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_tempText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(cui_tempText, -50);
    lv_obj_set_y(cui_tempText, -205);
    lv_obj_set_align(cui_tempText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_tempText, "92°C");
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(cui_tempText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(cui_tempText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);
    lv_obj_set_style_pad_left(cui_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_tempText, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_tempText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DIALS_NUM);
    children[UI_COMP_DIALS_DIALS] = cui_dials;
    children[UI_COMP_DIALS_TEMPTARGET] = cui_tempTarget;
    children[UI_COMP_DIALS_TEMPGAUGE] = cui_tempGauge;
    children[UI_COMP_DIALS_PRESSURETARGET] = cui_pressureTarget;
    children[UI_COMP_DIALS_PRESSUREGAUGE] = cui_pressureGauge;
    children[UI_COMP_DIALS_PRESSURETEXT] = cui_pressureText;
    children[UI_COMP_DIALS_TEMPTEXT] = cui_tempText;
    lv_obj_add_event_cb(cui_dials, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dials, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dials_create_hook(cui_dials);
    return cui_dials;
}
